export const shopActionTypes = {
    UPDATE_COLLECTIONS_PENDING : 'UPDATE_COLLECTIONS_PENDING',
    UPDATE_COLLECTIONS_SUCCESS : 'UPDATE_COLLECTIONS_SUCCESS',
    UPDATE_COLLECTIONS_FAIL : 'UPDCATE_COLLECTIONS_FAIL'

}