export const userActionTypes = {
    SET_CURRENT_USER :'SET_CURRENT_USER',
    EMAIL_SIGNIN_START : 'EMAIl_SIGNIN_START',
    GOOGLE_SIGNIN_START : 'GOOGLE_SIGNIN_START',
    SIGNIN_SUCCESS : 'SIGNIN_SUCCESS',
    SIGNIN_FAIL : 'SIGNIN_FAIL',
    USER_SESSION_CHECK : 'USER_SESSION_CHECK', 
    SIGN_OUT_START: 'SIGN_OUT_START',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
    SIGN_OUT_FAIL: 'SIGNOUT_FAIL',
    SIGN_UP_START: 'SIGN_UP_START',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAIL: 'SIGN_UP_FAIL'
}